In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [10]:
URL = "https://www.worldometers.info/coronavirus/"
page = requests.get(URL)

In [11]:
soup = BeautifulSoup(page.content, 'lxml')

In [18]:
table = soup.find('table')
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">TotÂ Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>119,089,076</td>
<td>+9,164</td>
<td>1,563,812</td>
<td>+72</td>
<td>114,565,751</td>
<td>+5,362</td>
<td>2,959,513</td>
<td>8,064</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>198,978,490</td>
<td>+239,214</td>
<td>1,497,796</td>
<td>+313</td>
<td>190,358,388</td>
<td>+107,703</td>
<td>7,122,306</td>
<td>9,554</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>237,988,579</td>
<td>+103,166</td>
<td>1,960,716</td>
<td>+187</td>
<td>232,312,670</td>
<td>+101,185</td>
<td>3,715,193</td>
<td>7,600</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>65,047,711</td>
<td>+2,440</td>
<td>1,335,585</td>
<td>+11</td>
<td>63,147,759</td>
<td>+11,205</td>
<td>564,367</td>
<td>10,163</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>12,993,814</td>
<td>+5,024</td>
<td>22,234</td>
<td>+19</td>
<td>12,761,454</td>
<td>+377</td>
<td>210,126</td>
<td>143</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,706,739</td>
<td>+760</td>
<td>258,076</td>
<td></td>
<td>12,016,757</td>
<td>+397</td>
<td>431,906</td>
<td>843</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>646,805,130</td>
<td>+359,768</td>
<td>6,638,234</td>
<td>+602</td>
<td>625,163,485</td>
<td>+226,229</td>
<td>15,003,411</td>
<td>36,367</td>
<td>82,979</td>
<td>851.6</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">100,519,026</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+9,159</td>
<td style="font-weight: bold; text-align:right;">1,104,954                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+72</td>
<td style="font-weight: bold; text-align:right">98,066,235</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,667</td>
<td style="text-align:right;font-weight:bold;">1,347,837</td>
<td style="font-weight: bold; text-align:right">2,881</td>
<td style="font-weight: bold; text-align:right">300,231</td>
<td style="font-weight: bold; text-align:right">3,300</td>
<td style="font-weight: bold; text-align:right">1,139,559,010</td>
<td style="font-weight: bold; text-align:right">3,403,647</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>303</td><td>0</td>
<td style="font-weight: bold; text-align:right">27</td>
<td style="font-weight: bold; text-align:right">0.2</td>
<td style="font-weight: bold; text-align:right">4,026</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,673,379</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+209</td>
<td style="font-weight: bold; text-align:right;">530,615                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,136,471</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">6,293</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,759</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">905,602,430</td>
<td style="font-weight: bold; text-align:right">643,809</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,651</td><td>2</td>
<td style="font-weight: bold; text-align:right">0.1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">4</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">37,778,417</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+91,814</td>
<td style="font-weight: bold; text-align:right;">158,859                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+88</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">36,882,249</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+28,607</td>
<td style="text-align:right;font-weight:bold;">737,309</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">576,026</td>
<td style="font-weight: bold; text-align:right">2,422</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>413</td><td>0</td>
<td style="font-weight: bold; text-align:right">1,400</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">11,242</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">36,419,717</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">157,657                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">35,736,000</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+37,800</td>
<td style="text-align:right;font-weight:bold;">526,060</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">434,170</td>
<td style="font-weight: bold; text-align:right">1,879</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>532</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,271</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">35,229,745</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">689,601                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">34,201,418</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">338,726</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">163,590</td>
<td style="font-weight: bold; text-align:right">3,202</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>312</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,573</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">27,031,319</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+71,476</td>
<td style="font-weight: bold; text-align:right;">30,454                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+41</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,061,126</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+54,475</td>
<td style="text-align:right;font-weight:bold;">939,739</td>
<td style="font-weight: bold; text-align:right">491</td>
<td style="font-weight: bold; text-align:right">526,619</td>
<td style="font-weight: bold; text-align:right">593</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,685</td><td>3</td>
<td style="font-weight: bold; text-align:right">1,392</td>
<td style="font-weight: bold; text-align:right">0.8</td>
<td style="font-weight: bold; text-align:right">18,308</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">24,654,770</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+127,422</td>
<td style="font-weight: bold; text-align:right;">49,434                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+153</td>
<td style="font-weight: bold; text-align:right">20,694,664</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+6,406</td>
<td style="text-align:right;font-weight:bold;">3,910,672</td>
<td style="font-weight: bold; text-align:right">334</td>
<td style="font-weight: bold; text-align:right">196,320</td>
<td style="font-weight: bold; text-align:right">394</td>
<td style="font-weight: bold; text-align:right">81,441,509</td>
<td style="font-weight: bold; text-align:right">648,498</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>5</td><td>2,540</td><td>2</td>
<td style="font-weight: bold; text-align:right">1,015</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">31,140</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">24,260,660</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">181,098                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">23,587,105</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">492,457</td>
<td style="font-weight: bold; text-align:right">250</td>
<td style="font-weight: bold; text-align:right">402,581</td>
<td style="font-weight: bold; text-align:right">3,005</td>
<td style="font-weight: bold; text-align:right">257,057,363</td>
<td style="font-weight: bold; text-align:right">4,265,608</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>333</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">8,172</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,000,101</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">196,821                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,734,087</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+4,520</td>
<td style="text-align:right;font-weight:bold;">69,193</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">350,377</td>
<td style="font-weight: bold; text-align:right">2,873</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>348</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,010</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,584,740</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+4,928</td>
<td style="font-weight: bold; text-align:right;">391,943                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+53</td>
<td style="font-weight: bold; text-align:right">20,992,153</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+5,863</td>
<td style="text-align:right;font-weight:bold;">200,644</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">148,037</td>
<td style="font-weight: bold; text-align:right">2,688</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>

In [37]:
headers = [header.text for header in table.select('thead tr th')]

results = [{headers[i]: cell.text for i, cell in enumerate(row.findAll("td"))} for row in table.select("tbody tr")]
headers

['#',
 'Country,Other',
 'TotalCases',
 'NewCases',
 'TotalDeaths',
 'NewDeaths',
 'TotalRecovered',
 'NewRecovered',
 'ActiveCases',
 'Serious,Critical',
 'Tot\xa0Cases/1M pop',
 'Deaths/1M pop',
 'TotalTests',
 'Tests/\n1M pop\n',
 'Population',
 'Continent',
 '1 Caseevery X ppl',
 '1 Deathevery X ppl',
 '1 Testevery X ppl',
 'New Cases/1M pop',
 'New Deaths/1M pop',
 'Active Cases/1M pop']